from alembic import op
import sqlalchemy as sa

revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name',sa.String(120),nullable=False),sa.Column('email',sa.String(255),nullable=False),sa.Column('password_hash',sa.String(512),nullable=False),sa.Column('preferred_language',sa.String(30),nullable=False,server_default='hin_Deva'),sa.Column('account_role',sa.String(20),nullable=False,server_default='student'),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('updated_at',sa.DateTime(timezone=True)))
    op.create_index('ix_users_email','users',['email'],unique=True)
    op.create_index('ix_users_account_role','users',['account_role'])
    op.create_table('groups',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name',sa.String(160),nullable=False),sa.Column('join_code',sa.String(32),nullable=False),sa.Column('grade',sa.String(50),nullable=False,server_default='Grade 2'),sa.Column('subject',sa.String(100),nullable=False,server_default='Environmental Studies'),sa.Column('owner_id',sa.Integer,sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_index('ix_groups_join_code','groups',['join_code'],unique=True); op.create_index('ix_groups_owner_id','groups',['owner_id'])
    op.create_table('memberships',sa.Column('id',sa.Integer,primary_key=True),sa.Column('group_id',sa.Integer,sa.ForeignKey('groups.id'),nullable=False),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id'),nullable=False),sa.Column('role',sa.String(30),nullable=False,server_default='student'),sa.Column('joined_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('group_id','user_id',name='uq_membership_group_user'))
    op.create_index('ix_memberships_group_id','memberships',['group_id']); op.create_index('ix_memberships_user_id','memberships',['user_id'])
    op.create_table('lesson_versions',sa.Column('id',sa.Integer,primary_key=True),sa.Column('lesson_id',sa.Integer,nullable=False),sa.Column('version_number',sa.Integer,nullable=False,server_default='1'),sa.Column('source_text',sa.Text,nullable=False),sa.Column('clean_transcript',sa.Text,nullable=False),sa.Column('learning_objectives_json',sa.Text,nullable=False),sa.Column('concepts_json',sa.Text,nullable=False),sa.Column('ai_explanation_json',sa.Text,nullable=False),sa.Column('activities_json',sa.Text,nullable=False),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.Column('published_at',sa.DateTime(timezone=True)),sa.Column('created_by',sa.Integer,sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_index('ix_lesson_versions_lesson_id','lesson_versions',['lesson_id'])
    op.create_table('lessons',sa.Column('id',sa.Integer,primary_key=True),sa.Column('group_id',sa.Integer,sa.ForeignKey('groups.id'),nullable=False),sa.Column('title',sa.String(200),nullable=False),sa.Column('grade',sa.String(50),nullable=False,server_default='Grade 2'),sa.Column('subject',sa.String(100),nullable=False,server_default='Environmental Studies'),sa.Column('topic',sa.String(160),nullable=False,server_default=''),sa.Column('source_language',sa.String(30),nullable=False,server_default='hin_Deva'),sa.Column('status',sa.String(40),nullable=False,server_default='DRAFT'),sa.Column('current_version_id',sa.Integer,sa.ForeignKey('lesson_versions.id')),sa.Column('created_by',sa.Integer,sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('updated_at',sa.DateTime(timezone=True)))
    op.create_index('ix_lessons_group_id','lessons',['group_id']); op.create_index('ix_lessons_status','lessons',['status']); op.create_index('ix_lessons_group_status','lessons',['group_id','status'])
    op.create_table('translations',sa.Column('id',sa.Integer,primary_key=True),sa.Column('lesson_version_id',sa.Integer,sa.ForeignKey('lesson_versions.id'),nullable=False),sa.Column('source_language',sa.String(30),nullable=False),sa.Column('target_language',sa.String(30),nullable=False),sa.Column('translated_text',sa.Text,nullable=False),sa.Column('confidence',sa.Float,nullable=False,server_default='0'),sa.Column('flags_json',sa.Text,nullable=False),sa.Column('validation_json',sa.Text,nullable=False),sa.Column('verification_status',sa.String(40),nullable=False,server_default='UNVERIFIED'),sa.Column('teacher_edited',sa.Boolean,nullable=False,server_default=sa.text('0')),sa.Column('native_review_status',sa.String(30),nullable=False,server_default='NOT_REVIEWED'),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('updated_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('lesson_version_id','target_language',name='uq_translation_version_language'))
    op.create_index('ix_translations_lesson_version_id','translations',['lesson_version_id'])
    op.create_table('artifacts',sa.Column('id',sa.Integer,primary_key=True),sa.Column('lesson_version_id',sa.Integer,sa.ForeignKey('lesson_versions.id'),nullable=False),sa.Column('type',sa.String(50),nullable=False),sa.Column('language',sa.String(30),nullable=False),sa.Column('path',sa.String(800),nullable=False),sa.Column('mime_type',sa.String(100),nullable=False),sa.Column('sha256',sa.String(64),nullable=False),sa.Column('size_bytes',sa.Integer,nullable=False,server_default='0'),sa.Column('metadata_json',sa.Text,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_index('ix_artifacts_lesson_version_id','artifacts',['lesson_version_id'])
    op.create_table('practice_questions',sa.Column('id',sa.Integer,primary_key=True),sa.Column('lesson_version_id',sa.Integer,sa.ForeignKey('lesson_versions.id'),nullable=False),sa.Column('concept_id',sa.String(80),nullable=False),sa.Column('prompt',sa.Text,nullable=False),sa.Column('options_json',sa.Text,nullable=False),sa.Column('correct_answer',sa.Text,nullable=False),sa.Column('explanation',sa.Text,nullable=False),sa.Column('language',sa.String(30),nullable=False),sa.Column('question_type',sa.String(30),nullable=False,server_default='mcq'),sa.Column('approved',sa.Boolean,nullable=False,server_default=sa.text('0')))
    op.create_index('ix_practice_questions_lesson_version_id','practice_questions',['lesson_version_id'])
    op.create_table('attempts',sa.Column('id',sa.Integer,primary_key=True),sa.Column('lesson_id',sa.Integer,sa.ForeignKey('lessons.id'),nullable=False),sa.Column('lesson_version_id',sa.Integer,sa.ForeignKey('lesson_versions.id'),nullable=False),sa.Column('student_id',sa.Integer,sa.ForeignKey('users.id'),nullable=False),sa.Column('answers_json',sa.Text,nullable=False),sa.Column('score',sa.Float,nullable=False,server_default='0'),sa.Column('concept_results_json',sa.Text,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('synced_at',sa.DateTime(timezone=True)))
    op.create_index('ix_attempts_lesson_id','attempts',['lesson_id']); op.create_index('ix_attempts_student_id','attempts',['student_id'])
    op.create_table('sync_records',sa.Column('id',sa.Integer,primary_key=True),sa.Column('device_id',sa.String(120),nullable=False),sa.Column('operation',sa.String(40),nullable=False),sa.Column('entity_type',sa.String(80),nullable=False),sa.Column('entity_id',sa.String(120),nullable=False),sa.Column('payload_json',sa.Text,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('processed_at',sa.DateTime(timezone=True)),sa.Column('attempt_count',sa.Integer,nullable=False,server_default='0'),sa.Column('last_error',sa.Text))
    op.create_index('ix_sync_records_device_id','sync_records',['device_id'])

def downgrade():
    op.drop_table('sync_records'); op.drop_table('attempts'); op.drop_table('practice_questions'); op.drop_table('artifacts'); op.drop_table('translations'); op.drop_table('lessons'); op.drop_table('lesson_versions'); op.drop_table('memberships'); op.drop_table('groups'); op.drop_table('users')
