import { useEffect, useState } from 'react';
import { Database, RefreshCw, Trash2, Wifi, WifiOff } from 'lucide-react';
import { Page, SectionTitle } from '../components/Shell';
import { Button, Card, Status, useToast } from '../components/UI';
import { all, clearOfflineContent } from '../lib/idb';
import { pendingCount, syncNow } from '../lib/sync';

export default function OfflinePage() {
  const [cached, setCached] = useState(0); const [pending, setPending] = useState(0); const [online, setOnline] = useState(navigator.onLine); const [busy, setBusy] = useState(false); const { push } = useToast();
  const load = async () => { setCached((await all<any>('lessons')).length); setPending(await pendingCount()); };
  useEffect(() => { void load(); const on = () => { setOnline(true); void load(); }; const off = () => setOnline(false); addEventListener('online', on); addEventListener('offline', off); return () => { removeEventListener('online', on); removeEventListener('offline', off); }; }, []);
  const sync = async () => { setBusy(true); const result = await syncNow(); setBusy(false); await load(); push(result.ok ? `Sync finished. ${result.count} item(s) processed.` : 'No sync occurred. Check your connection.', result.ok ? 'success' : 'error'); };
  const clear = async () => { if (!window.confirm('Clear cached lesson content and pending offline work from this browser?')) return; await clearOfflineContent(); await load(); push('Offline cache cleared.'); };
  return <Page eyebrow="OFFLINE-FIRST" title="Your downloaded classroom" subtitle="Published lesson packs are designed to survive connectivity drops. Learner work waits safely in the sync queue until the network returns."><div className="offline-banner-large">{online ? <Wifi size={19} /> : <WifiOff size={19} />}<div><strong>{online ? 'Online · synchronization available' : 'Offline · cached content stays usable'}</strong><span>{online ? 'You can sync pending learner work now.' : 'Reconnect later to synchronize pending attempts.'}</span></div></div><div className="metric-grid metric-grid-two"><Card><div className="metric-icon"><Database /></div><strong>{cached}</strong><span>Cached lesson packs</span><small>Stored in IndexedDB</small></Card><Card><div className="metric-icon"><RefreshCw /></div><strong>{pending}</strong><span>Pending sync</span><small>Offline learner attempts</small></Card></div><div className="button-row"><Button onClick={() => void sync()} disabled={busy || !online}><RefreshCw size={16} className={busy ? 'spin' : ''} />{busy ? 'Syncing…' : 'Sync now'}</Button><Button variant="danger" onClick={() => void clear()}><Trash2 size={16} /> Clear offline data</Button></div><Card><SectionTitle title="What learners can do offline" subtitle="The offline target is learning, not full generative AI." /><div className="offline-grid"><div>✓ Open published lesson text</div><div>✓ Switch between cached language content</div><div>✓ Play cached audio</div><div>✓ View worksheet + prepared activities</div><div>✓ Complete prepared practice</div><div>✓ Queue answers for later sync</div></div><p className="muted small">The TTS and translation models remain on the teacher/development machine. Students consume the approved, synchronized lesson package.</p></Card></Page>;
}
